# joint_limits.yaml allows the dynamics properties specified in the URDF to
# be overwritten or augmented as needed
# Specific joint properties can be changed with the keys
# [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    max_position: 6.283
    min_position: -6.283
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: true
    max_acceleration: 0.2
  joint_2:
    max_position: 1.6
#    min_position: ---
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: true
    max_acceleration: 0.2
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: true
    max_acceleration: 0.2
  joint_4:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: true
    max_acceleration: 0.2
